config/routes.rb
Motivator::Application.routes.draw do

  root :to => "static_pages#index"
  match "/index2" => "static_pages#index2"

  resources :creditcards

  resources :goals do
    resources :pledges
  end

  resources :steps

  resources :goals do
    resources :objectives
  end

  resources :goals do
     resources :charges
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  end

app/views/shared/_alerts.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>

app/views/shared/_footer.html.erb
<div class="navbar navbar-bottom">
  <div class="navbar-inner">
    <div class="container">

      <ul class="nav pull-left">
        <li><a href="<%=goals_path%>"><b>Motivator</b></a></li>
        <li><a href="#">&copy; GSD 2012</a></li>
      </ul>

      <ul class="nav pull-right">
        <li><a href="http://devbootcamp.com">Brought to you by Dev Bootcamp Alumni:</a>
        <li><a href="http://lifmus.com">Andrew Lin</a></li>
        <li><a href="http://www.jessieayoung.com">Jessie Young</a></li>
        <li><a href="http://dladowitz.github.com">David Ladowitz</a></li>
        <li><a href="http://about.me/djreyes">Jeremy Reyes</a></li>
      </ul>

    </div><!--/.container -->
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-fixed-top">


  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <a class="brand" href="<%=goals_path%>"><b>Motivator</b></a>

      <ul class="nav pull-right nav-collapse">
      <% if signed_in? %>
        <li><%= link_to "Community Goals", goals_path%></li>
        <li><%= link_to "Create a New Goal", new_goal_path%></li>
        <li><%= link_to "Signed in as #{current_user.email}", edit_user_registration_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete   %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
      </ul>

    </div><!--/.container -->
  </div>
</div>

<a href="https://github.com/you"><img style="position: absolute; top: 40px; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png" alt="Fork me on GitHub"></a>