config/routes.rb
Motivator::Application.routes.draw do

  root :to => "static_pages#index"
  match "/index2" => "static_pages#index2"

  resources :creditcards

  resources :goals do
    resources :pledges
  end

  resources :steps

  resources :goals do
    resources :objectives
  end

  resources :goals do
     resources :charges
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  end

app/controllers/creditcards_controller.rb
class CreditcardsController < ApplicationController
  before_filter :authenticate_user!

  def new
  end

  def create
    @goal = Goal.find(params[:goal_id])

    current_user.create_stripe_customer_id(params[:stripeToken])

    redirect_to creditcard_path(@goal)
  end

  def show
    @goal = Goal.find(params[:id])
  end
end

# test card: 4242424242424242

app/helpers/creditcards_helper.rb
module CreditcardsHelper
end

app/views/creditcards/new.html.erb
<script type="text/javascript" src="https://js.stripe.com/v1/"></script>
<form action="/creditcards" method="post" id="payment-form">
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />

  <div class="form-row">

    <label>Card Number</label>
    <input type="text" size="20" autocomplete="off" class="card-number" id="card-number" value="4242424242424242"/>
  </div>

  <div class="form-row">
    <label>CVC</label>
    <input type="text" size="4" autocomplete="off" class="card-cvc" id="card-cvc" value="123"/>
  </div>

  <div class="form-row">
    <label>Expiration (MM/YYYY)</label>
    <input type="text" size="2" class="card-expiry-month" id="card-expiry-month" value="11"/>
    <span> / </span>
    <input type="text" size="4" class="card-expiry-year" id="card-expiry-year" value="2016"/>
  </div>

  <%= hidden_field_tag :goal_id, params[:goal_id] %>

  <button type="submit" class="submit-button btn btn-success">Save Credit Card</button>

</form>

<img src="/images/green-card.png">

app/views/creditcards/show.html.erb
<div class="pledge_form_2"> Your goal: <b><%= @goal.description %></b></div>
<div class="pledge_form_2"> Your pledge amount: <b>$<%= @goal.pledge.amount %></b></div>
<div class="pledge_form_2"> Confirm?</div>
<%= button_to "YES", goal_charges_path(@goal), :class => "btn btn-success btn-large"%>
<%= button_to "Change Pledge Amount", edit_goal_pledge_path(@goal, @goal.pledge), :method => "get", :class => "btn btn-info btn-large"%>