config/routes.rb
Motivator::Application.routes.draw do

  root :to => "static_pages#index"
  match "/index2" => "static_pages#index2"

  resources :creditcards

  resources :goals do
    resources :pledges
  end

  resources :steps

  resources :goals do
    resources :objectives
  end

  resources :goals do
     resources :charges
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  end

app/models/step.rb
class Step < ActiveRecord::Base
  attr_accessible :completed_at, :objective_id, :image
  belongs_to :objective, :class_name => "Objective", :foreign_key => "objective_id"

  validates_presence_of :completed_at, :objective_id
  validates_uniqueness_of :completed_at, :scope => :objective_id #BUGBUG completed_at does not take into account time

  mount_uploader :image, ImageUploader
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController

  def index
    @steps = current_user.steps.all
  end

  def update
    @step = current_user.steps.find(params[:id])
    @step.image = params[:step][:image]
    @step.save
    redirect_to steps_path
  end


  def edit
    @step = current_user.steps.find(params[:id])
  end

  def create
    @goal = current_user.goals.find(params[:goal_id])
    @step = @goal.objectives.first.steps.new :completed_at => Time.now.to_date
    if @step.save
      redirect_to @goal
    else
      redirect_to :back, alert: 'You already recorded that step today'
    end
  end

  def show
    @step = current_user.steps.find(params[:id])
  end


  def new
    @step = current_user.steps.find(params[:id])

  end

end

app/views/steps/edit.html.erb
<%= form_for @step, :html => {:multipart => true} do |f| %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.file_field :image %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/steps/index.html.erb
<% @steps.each do |step|%>
<%= link_to "Step #{step.id}", step_path(step) %>  <%= link_to "Edit step #{step.id}", edit_step_path(step) %><br />



<div id="images">
  <% @steps.each do |step| %>
    <div class="image">
      <%= image_tag step.image_url.to_s %>
    </div>
  <% end %>
  <div class="clear"></div>
</div>

<% end %>

app/views/steps/show.html.erb
<%= @step.inspect %>