config/routes.rb
Motivator::Application.routes.draw do

  root :to => "static_pages#index"
  match "/index2" => "static_pages#index2"

  resources :creditcards

  resources :goals do
    resources :pledges
  end

  resources :steps

  resources :goals do
    resources :objectives
  end

  resources :goals do
     resources :charges
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  end

app/models/goal.rb
class Goal < ActiveRecord::Base
  attr_accessible :description, :due_date, :user_id, :objectives_attributes, :created_at, :public
  validates_presence_of :user_id, :description, :due_date
  belongs_to :user
  has_many :objectives, :inverse_of => :goal, :dependent => :destroy
  has_many :steps, :through => :objectives
  has_many :charges
  has_one :pledge
  accepts_nested_attributes_for :objectives
  validates_datetime :due_date, :on_or_after => :two_weeks_ahead, :on_or_before => :one_year_ahead
  validates_length_of :description, :maximum => 140

  def last_step
    # self.steps[self.total_steps - 1]
    sorted = self.steps.all(:order => :completed_at)
    sorted[self.total_steps - 1]
  end

  def finished_date
    if self.steps.count >= self.total_steps
      self.last_step.completed_at
    end
  end

  def readable_date
    self.due_date.to_date.to_formatted_s(:long)
  end

  def duration
    (self.due_date.to_date - self.created_at.to_date).to_i
  end

  def duration_in_weeks ## unrounded float
    (self.due_date.to_date - self.created_at.to_date) / 7
  end

  def weekly_rate
    self.objectives.first.frequency
  end

  def total_steps
    (self.duration_in_weeks * self.weekly_rate).round
  end

  def elapsed_days
    (Time.now.to_date - self.created_at.to_date).to_i
  end

  def percentage_complete
    completed = ((self.objectives.first.steps.count.to_f / total_steps) * 100 ).floor
    if completed > 100
      100
    else
      completed
    end
  end

  def expected_percentage_complete
    ((self.elapsed_days.to_f / self.duration) * 100).floor
  end

  def pledge_amount
    # TODO remove this method; goal.pledge.amount is equivalent
    # TODO add migration to set default value of amount to 0
    # TODO change pledge.amount field from decimal to integer
    self.pledge ? self.pledge.amount : 0
  end

  def full_pledge_amount_refunded?
    pledge.refunded_back >= pledge_amount
  end

  def step_value
    (self.pledge_amount.to_f / self.total_steps)#.round(2) # TODO May need to put this back.
  end

  def pledge_amount_earned_back
    @earned = self.step_value * self.objectives.first.steps.count
      if @earned > self.pledge_amount
        self.pledge_amount
      else
        @earned
      end
  end

  def initial_charge
    charges.initial_charge.first
  end

  def step_count_for_previous_period(num = 7)
    steps.where("(completed_at BETWEEN ? AND ?)", Time.now - num.days, Time.now).count
  end

  def nonrefunded_step_count_for_previous_week(num = 7)
    steps.where("(completed_at BETWEEN ? AND ?) AND refunded_at IS NULL", Time.now - num.days, Time.now).count
  end

  def nonrefunded_steps_for_previous_week(num = 7)
    steps.where("(completed_at BETWEEN ? AND ?) AND refunded_at IS NULL", Time.now - num.days, Time.now)
  end

  def refund_amount_for_previous_week
    # nonrefunded_step_count_for_previous_week * step_value
    nonrefunded_steps_for_previous_week.count * step_value
  end

  def weekly_goal_refund
    amount_to_be_refunded = refund_amount_for_previous_week
    if amount_to_be_refunded > 0 && !full_pledge_amount_refunded?
      user.refund_money((refund_amount_for_previous_week * 100).to_i, initial_charge.stripe_charge_id, self)
      nonrefunded_steps_for_previous_week.each do |step|
        step.refunded_at = Time.now
        step.save
      end
      pledge.refunded_back += (amount_to_be_refunded * 100).to_i
      pledge.save
    else
      # TODO Send email to encourage them to do their steps.
    end
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index]

  def index
    @goals = signed_in? ? current_user.goals : []
    @public_goals = Goal.find_all_by_public(true) - @goals
  end

  def show
    @goal = Goal.find(params[:id])
    @steps_completed_at = []
    @steps_by_date = @goal.steps.each do |step|
      @steps_completed_at << step.completed_at.to_date
    end
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    if @goal.public == false
      redirect_to goals_path, notice: 'That is a private goal'
    end unless @goal.user == current_user
  end

  def new
    @goal = Goal.new
    @goal.objectives.build
  end

  def create
    @goal = current_user.goals.new(params[:goal])
    if @goal.save
      redirect_to new_goal_pledge_path(@goal), notice: 'Goal was successfully created.'
    else
      render action: "new"
    end
  end

  def edit
    @goal = current_user.goals.find(params[:id])
    @objective = @goal.objectives.first #BUGBUG only works for one objective
    @days = []
    # @objective.build_steps
    7.times { | num | @days << Time.now - num.days }
  end

  def update
    @goal = current_user.goals.find(params[:id])
    @objective = @goal.objectives.find(params[:objective_id])
    # accepts nested attributes, related to line 30
    params[:day].each do |key, value|
      @objective.steps.find_or_create_by_completed_at(:completed_at => value)
    end

    redirect_to @goal
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_expected_progress.html.erb
<div class="progress progress-info">
  <div class="bar" data-percentage="<%= goal.expected_percentage_complete %>"></div>
</div>

app/views/goals/_form.html.erb
<%= form_for @goal do |f| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- GOAL DESCRIPTION -->
  <div class="row-fluid">
    <div class="span6 field goal_form">
      My goal is to
    </div>

    <div class="span6 field goal_form">
      <%= f.text_field :description, :placeholder=>"Complete an Iron Man" %>
    </div>
  </div>

  <!-- GOAL DUE DATE -->
  <div class="row-fluid">
    <div class="span6 field goal_form">
      by
    </div>

    <div class="span6 field goal_form">
      <%= f.text_field :due_date, :placeholder=>"October 18, 2012"%>
    </div>
  </div>

  <%= f.fields_for :objectives do |objective_fields| %>

    <!-- OBJECTIVE DESCRIPTION -->
    <div class="row-fluid">
      <div class="span6 field goal_form">
        To achieve this, I will
      </div>

      <div class="span6 field goal_form">
        <%= objective_fields.text_field :description, :placeholder=>"train with my team"%>
      </div>
    </div>

    <!-- OBJECTIVE FREQUENCY -->
    <div class="row-fluid">
      <div class="span6 field goal_form">
        at least
      </div>


      <div class="span3 field goal_form">
         <%= objective_fields.select(:frequency, (1..7).map { |n| ["#{n}","#{n}"] })%>
      </div>

      <div class="span3 field goal_form_2">
        times per week.<br /><br />
      </div>
    </div>

  <% end %>

  <!-- GOAL PRIVACY -->
  <div class="row-fluid">
    <div class="span6 field goal_form">
      This is a
    </div>

    <div class="span3 field goal_form">
      <%= f.select(:public, [['Public', 'true'], ['Private', 'false']])%>
    </div>

    <div class="span3 field goal_form_2">
      goal.<br /><br />
    </div>
  </div>

  <div class="row-fluid centerize">
    <%= f.submit "I'm ready to get motivated", :class=>"btn btn-success btn-large goal_form" %>
  </div>

<% end %>

app/views/goals/_pie.html.erb
<div id="progress-pie-chart"></div>
<script type="text/javascript">
var w = 275,
    h = 275,
    radius = Math.min(w, h) / 2,
    // data = d3.range(10).map(Math.random).sort(d3.descending),
    data = [<%= @goal.pledge_amount - @goal.pledge_amount_earned_back %>, <%= @goal.pledge_amount_earned_back %> ].sort(d3.descending),
    color = d3.scale.linear()
    .range(["#F7F7F7","#62C462"])
    arc = d3.svg.arc().outerRadius(radius),
    donut = d3.layout.pie();

var vis = d3.select("#progress-pie-chart").append("svg:svg")
    .data([data])
    .attr("width", w)
    .attr("height", h);

var arcs = vis.selectAll("g.arc")
    .data(donut)
  .enter().append("g")
    .attr("class", "arc")
    .attr("transform", "translate(" + radius + "," + radius + ")");

var paths = arcs.append("path")
    .attr("fill", function(d, i) { return color(i); });

var center_group = vis.append("svg:g")
  .attr("class", "center_group")
  .attr("transform", "translate(" + (w/2) + "," + (h/2) + ")");


var totalLabel = center_group.append("svg:text")
  .attr("class", "label")
  .attr("dy", -15)
  .attr("text-anchor", "middle") // text-align: right
  .text("Amount Earned Back");


  //TOTAL TRAFFIC VALUE
var totalValue = center_group.append("svg:text")
  .attr("class", "total")
  .attr("dy", 7)
  .attr("text-anchor", "middle") // text-align: right
  .text("$<%= @goal.pledge_amount_earned_back.floor%>");





paths.transition()
    .ease("bounce")
    .duration(2000)
    .attrTween("d", tweenPie);

paths.transition()
    .ease("elastic")
    .delay(function(d, i) { return 2000 + i * 50; })
    .duration(750)
    .attrTween("d", tweenDonut);

paths.transition()
    .ease("elastic")
    .delay(function(d, i) { return 2000 + i * 50; })
    .duration(750)
    .attrTween("d", tweenDonut);




function tweenPie(b) {
  b.innerRadius = 0;
  var i = d3.interpolate({startAngle: 0, endAngle: 0}, b);
  return function(t) {
    return arc(i(t));
  };
}

function tweenDonut(b) {
  b.innerRadius = radius * .6;
  var i = d3.interpolate({innerRadius: 0}, b);
  return function(t) {
    return arc(i(t));
  };
}





</script>

app/views/goals/_progress.html.erb
<div class="progress progress-success progress-striped active" id="index_progress">
  <div class="bar" data-percentage="<%= goal.percentage_complete %>"></div>
</div>

app/views/goals/edit.html.erb
<h1>My goal is to <%= @goal.description %></h1>
<h3>I will achieve this by <%= @goal.readable_date %></h3>
<!-- TODO: TEST ME! -->
<%= form_tag goal_path(@goal), :action => :update, :method => :put do %>
<h2>When did you last <%= @objective.description %>?</h2>
  <div>
  <% @days.each_with_index do |day, index| %>
    <% if day > Time.now %>
      <div style="color:grey"><%= day.strftime("%a %b #{day.day.ordinalize}") %></div>
    <% else %>
      <div style="color:green"><%= day.strftime("%a %b #{day.day.ordinalize}") %>
      <%= check_box_tag "day[#{index + 1}]", day, false %></div>
    <% end %>
  <% end %>
  </div>
  <%= hidden_field_tag :objective_id, @objective.id %>
  <%= submit_tag "Mark 'em done!", :class => "btn btn-primary" %>
<% end %>

app/views/goals/index.html.erb
<% if signed_in? %>
  <div class="span12">
    <h1>Here are your existing goals:</h1> <br/>
    <% @goals.each do |goal| %>
      <div class="well sidebar-nav row span4">
        <div class="profile_picture span1"><%= profile_pic_for goal.user %></div>
        <div class="span2">
          <%= link_to "#{goal.description} (#{goal.percentage_complete}% Complete)", goal %>
          <%= render :partial => "progress", :locals => { :goal => goal } %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<br />
<br />

<div class="span12">
	<h1>Here are all of the public goals:</h1>
	<br />
		<% @public_goals.each do |goal| %>
			<div class="well sidebar-nav row span4">
  			<div class="profile_picture span1"><%= profile_pic_for goal.user %></div>
  			<div class="span2">
    		<%= link_to "#{goal.description} (#{goal.percentage_complete}% Complete)", goal %>
    		<%= render :partial => "progress", :locals => { :goal => goal } %>
  			</div>
			</div>
		<% end %>
</div>

app/views/goals/new.html.erb
<h1>Make a new goal</h1>
<br /><br />

<%= render 'form' %>

app/views/goals/show.html.erb
<h1><%= @goal.description %></h1>
<h3>Goal Due Date: <%= @goal.readable_date %></h3>
<h3><%= @goal.objectives.first.description %></h3><br />

Progress:
<%= render :partial => "progress", :locals => { :goal => @goal } %>

Expected progress:
<%= render :partial => "expected_progress", :locals => { :goal => @goal } %>

<div class="row-fluid">
  <div class="span6">
    <%= render :partial => 'pie' %>
  </div>

  <div class="span6">
    <div class="row-fluid">
      <% if @goal.user == current_user%>
      <div class="well">
        <h4>Goal details:</h4><br />
        <ul>
          <li>You have earned $<%= @goal.pledge_amount_earned_back.floor %> of your original pledge of $<%= @goal.pledge_amount%>. </li>
          <li>You have completed <%= @goal.objectives.first.steps.count %> out of <%= @goal.total_steps %> steps toward your goal. </li>
        </ul>
      </div>
    </div>

    <div class="row-fluid">
      <%= button_to "I took a step today", steps_path(:goal_id => @goal), :class =>"btn btn-success btn-large goal_form", :method => "post" %>
      <%= link_to "Missed a day? Edit past days", edit_goal_path(@goal), :method => "get" %>
    </div>
  </div>
</div>

<div class="row-fluid" id="goals">
  <h3 id="month">
	<%= link_to "<", date: @date.prev_month %>
	<%= @date.strftime("%B %Y")%> Step History 
	<%= link_to ">", date: @date.next_month %>
  	</h3>
	<%= calendar @date do |date| %>
		<%= date.day %>
		<% if @steps_completed_at.include? date %>
			<ul class="unstyled centerize">
				<li><i class="icon-ok"></i><br /></li>
		<% end %>
		<% if @goal.finished_date && @goal.finished_date.to_date == date %>
				<li><%= image_tag "success_baby.jpeg" %></li>
			</ul>
		<% end %>
	<% end %>
</div>
      <% end %>